twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        profil_pic_dir: '/images/profile_pictures'
        # the value is the service's id
        NewsPanel: '@App\Service\NewsPanel'
