<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

use App\Entity\BlogPost;
use App\Entity\Article;

class ImportController extends AbstractController
{
    
    public function importPicture($page)
    {
        return $this->render('import/import_picture.html.twig', [
            'blogs_latest' => $this->getDoctrine()->getRepository(BlogPost::class)->findBlogByDate(),
            'articles_latest' => $this->getDoctrine()->getRepository(Article::class)->findArticleByDate(),
            'pages' => [
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '2', 'link' => '/import-picture/2'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
                ['numero' => '1', 'link' => '/import-picture/1'],
            ],
        ]);
    }
}
