
#--------------------------------------------------
# Start of HomeController's routes
#--------------------------------------------------

index:
    path: /
    controller: App\Controller\HomeController::index

pages:
    path: /pages
    controller: App\Controller\HomeController::pages

#--------------------------------------------------
# End of HomeController's routes
#--------------------------------------------------
