
#--------------------------------------------------
# Start of HomeController's routes
#--------------------------------------------------

index:
    path: /
    controller: App\Controller\HomeController::index

pages:
    path: /pages
    controller: App\Controller\HomeController::pages

blog:
    path: /blog
    controller: App\Controller\HomeController::blog

contact:
    path: /contact
    controller: App\Controller\HomeController::contact

#--------------------------------------------------
# End of HomeController's routes
#--------------------------------------------------

#--------------------------------------------------
# Start of BlogController's routes
#--------------------------------------------------

user_blog:
    path: /blog/{useruuid}
    controller: App\Controller\BlogController::ShowBlog
    defaults:
        useruuid: -1
    requirements:
        useruuid: '\d+'

#--------------------------------------------------
# End of BlogController's routes
#--------------------------------------------------
