
#--------------------------------------------------
# Start of HomeController's routes
#--------------------------------------------------
index:
    path: /
    controller: App\Controller\HomeController::index

pages:
    path: /pages
    controller: App\Controller\HomeController::pages

blog:
    path: /blog
    controller: App\Controller\HomeController::blog

contact:
    path: /contact
    controller: App\Controller\HomeController::contact

#--------------------------------------------------
# End of HomeController's routes
#--------------------------------------------------

#--------------------------------------------------
# Start of BlogController's routes
#--------------------------------------------------

user_blog:
    path: /blog/{username}
    controller: App\Controller\BlogController::ShowBlog
    defaults:
        username: ""
#--------------------------------------------------
# End of BlogController's routes
#--------------------------------------------------

#--------------------------------------------------
# Start of ArticleController's routes
#--------------------------------------------------
page:
    path: /pages/{pathTitle}
    controller: App\Controller\ArticleController::showPage
#--------------------------------------------------
# End of ArticleControllers routes
#--------------------------------------------------

#--------------------------------------------------
# Start of SecurityController's routes
#--------------------------------------------------
edit_user:
    path: /modify-account
    controller: App\Controller\SecurityController::editUserSelf
#--------------------------------------------------
# End of SecurityController's routes
#--------------------------------------------------
