#--------------------------------------------------
# Start of HomeController's routes
#--------------------------------------------------
index:
  path: /
  controller: App\Controller\HomeController::index

pages:
    path: /pages/{page}
    controller: App\Controller\HomeController::pages
    defaults:
        page: 1
    requirements: 
        page: '\d+'

blog:
    path: /blog/{page}
    controller: App\Controller\HomeController::blog
    defaults:
        page: 1
    requirements: 
        page: '\d+'

contact:
  path: /contact
  controller: App\Controller\HomeController::contact

#--------------------------------------------------
# End of HomeController's routes
#--------------------------------------------------

#--------------------------------------------------
# Start of BlogController's routes
#--------------------------------------------------

user_blog:
    path: /blog/{username}/{page}
    controller: App\Controller\BlogController::ShowBlog
    defaults:
        username: ""
        page: 1
    requirements: 
        page: '\d+'

user_blog_edit:
  path: /blog-post/{blogId}/edit
  controller: App\Controller\BlogController::EditBlogPost
  defaults:
    blogId: 1
  requirements: 
    blogId: '\d+'

user_blog_post:
    path: /blog-post/{blogId}
    controller: App\Controller\BlogController::ShowBlogId
    defaults:
        blogId: 1
    requirements: 
        blogId: '\d+'

user_blog_add:
  path: /blog-post/add
  controller: App\Controller\BlogController::AddBlogPost

#--------------------------------------------------
# End of BlogController's routes
#--------------------------------------------------

#--------------------------------------------------
# Start of ArticleController's routes
#--------------------------------------------------
add_page:
  path: /pages/add
  controller: App\Controller\ArticleController::addPage

page:
  path: /pages/{pathTitle}
  controller: App\Controller\ArticleController::showPage

edit:
  path: /pages/{pathTitle}/edit
  controller: App\Controller\ArticleController::editPage

get_image_path_in_page_edit_ajax:
  path: /images/{imageId}
  controller: App\Controller\ArticleController::GetImageLink
  methods: POST
  defaults:
    imageId: 0
  requirements:
    imageId: '\d+'
#--------------------------------------------------
# End of ArticleControllers routes
#--------------------------------------------------

#--------------------------------------------------
# Start of SecurityController's routes
#--------------------------------------------------
edit_user:
  path: /modify-account
  controller: App\Controller\SecurityController::editUserSelf
#--------------------------------------------------
# End of SecurityController's routes
#--------------------------------------------------

#--------------------------------------------------
# Start of ImportController's routes
#--------------------------------------------------
import_picture:
  path: /import-picture/{page}
  controller: App\Controller\ImportController::importPicture
  defaults:
    page: 1
  requirements:
    page: '\d+'

imported_picture_modif:
  path: /import-picture/modify/{imageId}
  controller: App\Controller\ImportController::modifyPicture
  defaults:
    iamgeId: 1
  requirements:
    imageId: '\d+'
#--------------------------------------------------
# End of ImportController's routes
#--------------------------------------------------

#--------------------------------------------------
# Start of ImportController's routes
#--------------------------------------------------
category_index:
    path: /category
    controller: App\Controller\CategoryController::index

category_list:
    path: /category/{name}
    controller: App\Controller\CategoryController::categoryList
#--------------------------------------------------
# End of ImportController's routes
#--------------------------------------------------

#--------------------------------------------------
# Start of About's routes
#--------------------------------------------------
about_user:
    path: /about/user/{username}
    controller: App\Controller\About::AboutUser
#--------------------------------------------------
# End of About's routes
#--------------------------------------------------


