
#--------------------------------------------------
# Start of HomeController's routes
#--------------------------------------------------
index:
    path: /
    controller: App\Controller\HomeController::index

pages:
    path: /pages/{page}
    controller: App\Controller\HomeController::pages
    defaults:
        page: 1
    requirements: 
        page: '\d+'

blog:
    path: /blog
    controller: App\Controller\HomeController::blog

contact:
    path: /contact
    controller: App\Controller\HomeController::contact

#--------------------------------------------------
# End of HomeController's routes
#--------------------------------------------------

#--------------------------------------------------
# Start of BlogController's routes
#--------------------------------------------------

user_blog:
    path: /blog/{username}
    controller: App\Controller\BlogController::ShowBlog
    defaults:
        username: ""
#--------------------------------------------------
# End of BlogController's routes
#--------------------------------------------------

#--------------------------------------------------
# Start of ArticleController's routes
#--------------------------------------------------
page:
    path: /pages/{pathTitle}
    controller: App\Controller\ArticleController::showPage
#--------------------------------------------------
# End of ArticleControllers routes
#--------------------------------------------------

#--------------------------------------------------
# Start of SecurityController's routes
#--------------------------------------------------
edit_user:
    path: /modify-account
    controller: App\Controller\SecurityController::editUserSelf
#--------------------------------------------------
# End of SecurityController's routes
#--------------------------------------------------

#--------------------------------------------------
# Start of ImportController's routes
#--------------------------------------------------
import_picture:
    path: /import-picture/{page}
    controller: App\Controller\ImportController::importPicture
    defaults:
        page: 1
    requirements: 
        page: '\d+'

imported_picture_modif:
    path: /import-picture/modify/{imageId}
    controller: App\Controller\ImportController::modifyPicture
    defaults:
        iamgeId: 1
    requirements: 
        imageId: '\d+'

#--------------------------------------------------
# End of ImportController's routes
#--------------------------------------------------

